# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mysql
    volumes:
      - data:/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8061:8080

volumes:
  data: {}

networks:
  default:
    name: mysql_network


# _____________________

# note:
# user = root
# password = mysql